site_name: Exandria Campaign
site_description: Campaign website for Scott's D&D Dweebs' Adventures in Exandria
site_author: NorthernScott
copyright: © 2025 NorthernScott. The 'Exandria' campaign setting is the property of Critical Role, LLC.

site_url: https://exu.northernscott.ca
repo_url: https://github.com/NorthernScott/exu-website
edit_uri: blob/main/docs/
dev_addr: 127.0.0.1:8000
remote_branch: main

use_directory_urls: true
markdown_extensions:
  - toc:
    permalink: true
  - sane_lists
  - admonition
  - pymdownx.snippets:
    base_path: !relative

plugins:
  - search:
    lang: en
    separator: '[\s\-]+'
    min_search_length: 3
    max_search_results: 10
  - mkdocs-git-revision-date-localized-plugin:
    enabled: true
    include_date: true
    include_time: false
    date_format: "MMMM Do YYYY"
    time_format: "h:mm A"
  - privacy
  - pub-meta:
    overview:
      enable: true
      default: auto
      key_name: slug
      dir_meta_file: README.md
    publish:
      search_in_hidden: false
      search_in_draft: false
      file_default: draft
      file_warn_on_missing: true
      dir_default: published
      dir_warn_on_missing: false
      key_name: publish
    redirect:
      enable: true
      key_name: redirect
    slug:
      enable: true
      mode: title
      warn_on_missing: true
      key_name: slug
    title:
      key_name: title
  - pub-obsidian:
    obsidian_dir: .obsidian
    templates_dir: templates
    backlinks:
      enabled: true
    callouts:
      enabled: true
      indentation: spaces
    comments:
      enabled: true
      inject_as_html: false
    links:
      wikilinks_enabled: true
      img_lazy: true
    vega:
      enabled: true
      vega_schema: https://vega.github.io/schema/vega/v5.json
      vega_lite_schema: https://vega.github.io/schema/vega-lite/v5.json

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: teal
      accent: deep orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: teal
      accent: deep orange

  font:
    text: IBM Plex Serif
    code: IBM Plex Mono

  language: en

  logo: assets/ampersand-logo.png
  favicon: assets/ampersand-logo.png
