site_name: Exandria Campaign
site_description: Campaign website for Scott's D&D Dweebs' Adventures in Exandria
site_author: NorthernScott
copyright: © 2025 NorthernScott. The 'Exandria' campaign setting is the property of Critical Role, LLC.

site_url: https://northernscott.ca/
repo_url: https://github.com/NorthernScott/exu-website/
edit_uri: blob/main/docs/
dev_addr: 127.0.0.1:8000
remote_branch: gh-pages
remote_name: origin

docs_dir: docs
site_dir: site

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

use_directory_urls: true

# nav:
#   - Home: index.md
#   - About:
#       - Ground Rules: Ground Rules.md
#       - House Rules: House Rules.md
#   - The World:
#       - Primer: world/World.md
#       - Map: world/map.md
#   - Sessions: blog/index.md

markdown_extensions:
  - nl2br
  - abbr
  - tables
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - admonition
  - toc:
      title: On this page
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: !relative
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      enabled: true
      lang: en
  - privacy
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - minify:
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
        remove_comments: true
  - callouts
  - glightbox

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: teal
      accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: teal
      accent: amber

  features:
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.path
    # - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - navigation.expand
    # - navigation.prune
    # - navigation.tabs
    # - navigation.tabs.sticky

  font:
    text: IBM Plex Serif
    code: IBM Plex Mono

  icon:
    repo: fontawesome/brands/github

  language: en

  logo: assets/images/ampersand-logo.png
  favicon: assets/images/ampersand-logo.png

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/aVwt8qPC

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/scripts/mathjax.js
  # - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  # - assets/scripts/tablesort.js
